/*
The Permission tree can only be a single step deep e.g

  {
    users: {
      readOne: "can_read_user",
      readAll: "can_read_all_users",
      delete: "can_delete_user",
    },
  };

  So users.readOne, is as far as you can go
*/

export const allPermissions = {
  users: {
    readOne: "can_read_user",
    readAll: "can_read_all_users",
    delete: "can_delete_user",
    update: "can_update_user",
    create: "can_create_user",
    updatePassword: "can_update_password",
  },
  auth: {
    activateAccount: "can_activate_account",
    deActivateAccount: "can_de_activate_account",
  },
  departments: {
    readOne: "can_read_department",
    readAll: "can_read_all_departments",
    delete: "can_delete_department",
    update: "can_update_department",
    create: "can_create_department",
  },
  employees: {
    readOne: "can_read_employee",
    readAll: "can_read_all_employees",
    delete: "can_delete_employee",
    update: "can_update_employee",
    create: "can_create_employee",
  },
  guest: {
    readOne: "can_read_guest",
    readAll: "can_read_all_guests",
    delete: "can_delete_guest",
    update: "can_update_guest",
    create: "can_create_guest",
  },
  permissions: {
    readOne: "can_read_permission",
    readAll: "can_read_all_permissions",
    delete: "can_delete_permission",
    update: "can_update_permission",
    create: "can_create_permission",
  },
  permissionOverides: {
    readOne: "can_read_permission_overide",
    readAll: "can_read_all_permission_overides",
    delete: "can_delete_permission_overide",
    update: "can_update_permission_overide",
    create: "can_create_permission_overide",
  },
  roleOverides: {
    readOne: "can_read_role_overide",
    readAll: "can_read_all_role_overides",
    delete: "can_delete_role_overide",
    update: "can_update_role_overide",
    create: "can_create_role_overide",
  },
  position: {
    readOne: "can_read_position",
    readAll: "can_read_all_positions",
    delete: "can_delete_position",
    update: "can_update_position",
    create: "can_create_position",
  },
  roles: {
    readOne: "can_read_role",
    readAll: "can_read_all_roles",
    delete: "can_delete_role",
    update: "can_update_role",
    create: "can_create_role",
  },
  rolePermissions: {
    readOne: "can_read_role_permission",
    readAll: "can_read_all_role_permissions",
    delete: "can_delete_role_permission",
    update: "can_update_role_permission",
    create: "can_create_role_permission",
  },
  activityLogs: {
    read: "can_read_activity_logs",
  },
  reservations: {
    readOne: "can_read_reservation",
    readAll: "can_read_all_reservations",
    delete: "can_delete_reservation",
    update: "can_update_reservation",
    create: "can_create_reservation",
    createManualReservation: "can_create_manual_reservation",
    updateManualReservationPay: "can_update_manual_reservation_pay",
    cancel: "can_cancel_reservation",
    updateRooms: "can_update_reservation_rooms",
    calendar: "can_read_calendar",
  },
  buildings: {
    readOne: "can_read_building",
    readAll: "can_read_all_buildings",
    delete: "can_delete_building",
    update: "can_update_building",
    create: "can_create_building",
  },
  rooms: {
    readOne: "can_read_room",
    readAll: "can_read_all_rooms",
    delete: "can_delete_room",
    update: "can_update_room",
    create: "can_create_room",
  },
  roomTypes: {
    readOne: "can_read_room_type",
    readAll: "can_read_all_room_types",
    delete: "can_delete_room_type",
    update: "can_update_room_type",
    create: "can_create_room_type",
  },
  rates: {
    readOne: "can_read_rate",
    readAll: "can_read_all_rates",
    delete: "can_delete_rate",
    update: "can_update_rate",
    create: "can_create_rate",
  },
  discounts: {
    readOne: "can_read_discount",
    readAll: "can_read_all_discounts",
    delete: "can_delete_discount",
    update: "can_update_discount",
    create: "can_create_discount",
  },
  taxes: {
    readOne: "can_read_tax",
    readAll: "can_read_all_taxes",
    delete: "can_delete_tax",
    update: "can_update_tax",
    create: "can_create_tax",
  },
  adminConfigurations: {
    update: "can_update_admin_configuration",
    read: "can_read_admin_configuration",
  },
  amenities: {
    readOne: "can_read_amenity",
    readAll: "can_read_all_amenities",
    delete: "can_delete_amenity",
    update: "can_update_amenity",
    create: "can_create_amenity",
  },
  roomTypeAmenities: {
    readOne: "can_read_room_type_amenity",
    readAll: "can_read_all_room_type_amenities",
    delete: "can_delete_room_type_amenity",
    update: "can_update_room_type_amenity",
    create: "can_create_room_type_amenity",
  },
  bedTypes: {
    readOne: "can_read_bed_type",
    readAll: "can_read_all_bedTypes",
    delete: "can_delete_bed_type",
    update: "can_update_bed_type",
    create: "can_create_bed_type",
  },
  roomTypeBedTypes: {
    readOne: "can_read_room_type_bed_type",
    readAll: "can_read_all_room_type_bed_types",
    delete: "can_delete_room_type_bed_type",
    update: "can_update_room_type_bed_type",
    create: "can_create_room_type_bed_type",
  },
  roomTypeReviews: {
    readOne: "can_read_room_type_review",
    readAll: "can_read_all_room_type_reviews",
    delete: "can_delete_room_type_review",
    update: "can_update_room_type_review",
    create: "can_create_room_type_review",
  },
  invoices: {
    readOne: "can_read_invoice",
    readAll: "can_read_all_invoices",
    delete: "can_delete_invoice",
    update: "can_update_invoice",
    create: "can_create_invoice",
  },
  content: {
    adminDashboard: "can_read_admin_dashboard",
  },
  parkingSectionTypes: {
    readOne: "can_read_parking_section_type",
    readAll: "can_read_all_parking_section_types",
    delete: "can_delete_parking_section_type",
    update: "can_update_parking_section_type",
    create: "can_create_parking_section_type",
  },
  parkingSections: {
    readOne: "can_read_parking_section",
    readAll: "can_read_all_parking_sections",
    delete: "can_delete_parking_section",
    update: "can_update_parking_section",
    create: "can_create_parking_section",
  },
  parkingSpots: {
    readOne: "can_read_parking_spot",
    readAll: "can_read_all_parking_spots",
    delete: "can_delete_parking_spot",
    update: "can_update_parking_spot",
    create: "can_create_parking_spot",
  },
  parkingReservations: {
    readOne: "can_read_parking_reservation",
    readAll: "can_read_all_parking_reservations",
    delete: "can_delete_parking_reservation",
    update: "can_update_parking_reservation",
    create: "can_create_parking_reservation",
  },
  bills: {
    readOne: "can_read_bill",
    readAll: "can_read_all_bills",
    delete: "can_delete_bill",
    update: "can_update_bill",
    create: "can_create_bill",
  },
  billItems: {
    readOne: "can_read_bill_item",
    readAll: "can_read_all_bill_items",
    delete: "can_delete_bill_item",
    update: "can_update_bill_item",
    create: "can_create_bill_item",
  },
  restaurantItemCategorys: {
    readOne: "can_read_restaurant_item_category_item",
    readAll: "can_read_all_restaurant_item_category_items",
    delete: "can_delete_restaurant_item_category_item",
    update: "can_update_restaurant_item_category_item",
    create: "can_create_restaurant_item_category_item",
  },
  restaurantItems: {
    readOne: "can_read_restaurant_item",
    readAll: "can_read_all_restaurant_item",
    delete: "can_delete_restaurant_item",
    update: "can_update_restaurant_item",
    create: "can_create_restaurant_item",
  },
  restaurantCarts: {
    readOne: "can_read_restaurant_cart",
    readAll: "can_read_all_restaurant_carts",
    delete: "can_delete_restaurant_cart",
    update: "can_update_restaurant_cart",
    create: "can_create_restaurant_cart",
  },
  restaurantCartItems: {
    readOne: "can_read_restaurant_cart_item",
    readAll: "can_read_all_restaurant_cart_items",
    delete: "can_delete_restaurant_cart_item",
    update: "can_update_restaurant_cart_item",
    create: "can_create_restaurant_cart_item",
  },
  restaurantOrders: {
    readOne: "can_read_restaurant_restaurant_order",
    readAll: "can_read_all_restaurant_restaurant_orders",
    delete: "can_delete_restaurant_restaurant_order",
    update: "can_update_restaurant_restaurant_order",
    create: "can_create_restaurant_restaurant_order",
  },
};
